"""
export_ppo_cnn_agent.py

Convert a trained PPO/CNN PyTorch checkpoint into a standalone
`src/agents/proposed_agent.py` submission file.

This file does not train anything. It only exports a fixed policy.

Expected checkpoint format:
    {"model_state_dict": model.state_dict()}
    or {"state_dict": model.state_dict()}
    or directly model.state_dict()

Expected model architecture:
    cnn.0 = Conv2d(6, 16, kernel_size=3, padding=1, stride=1)
    cnn.2 = Conv2d(16, 32, kernel_size=3, padding=1, stride=2)
    cnn.4 = Conv2d(32, 64, kernel_size=3, padding=1, stride=2)
    vector_net.0 = Linear(7, 32)
    shared.0 = Linear(64 * 8 * 8 + 32, 256)
    shared.2 = Linear(256, 128)
    policy_head = Linear(128, 9)

The value head is ignored because evaluation only needs actions.
"""

from __future__ import annotations

import argparse
import base64
import io
from pathlib import Path
from typing import Dict

import numpy as np
import torch


REQUIRED_KEYS = [
    "cnn.0.weight",
    "cnn.0.bias",
    "cnn.2.weight",
    "cnn.2.bias",
    "cnn.4.weight",
    "cnn.4.bias",
    "vector_net.0.weight",
    "vector_net.0.bias",
    "shared.0.weight",
    "shared.0.bias",
    "shared.2.weight",
    "shared.2.bias",
    "policy_head.weight",
    "policy_head.bias",
]

KEY_MAP = {
    "cnn.0.weight": "conv0_w",
    "cnn.0.bias": "conv0_b",
    "cnn.2.weight": "conv1_w",
    "cnn.2.bias": "conv1_b",
    "cnn.4.weight": "conv2_w",
    "cnn.4.bias": "conv2_b",
    "vector_net.0.weight": "vec0_w",
    "vector_net.0.bias": "vec0_b",
    "shared.0.weight": "shared0_w",
    "shared.0.bias": "shared0_b",
    "shared.2.weight": "shared1_w",
    "shared.2.bias": "shared1_b",
    "policy_head.weight": "policy_w",
    "policy_head.bias": "policy_b",
}


def load_state_dict(checkpoint_path: Path) -> Dict[str, torch.Tensor]:
    checkpoint = torch.load(checkpoint_path, map_location="cpu")

    if isinstance(checkpoint, dict) and "model_state_dict" in checkpoint:
        state_dict = checkpoint["model_state_dict"]
    elif isinstance(checkpoint, dict) and "state_dict" in checkpoint:
        state_dict = checkpoint["state_dict"]
    elif isinstance(checkpoint, dict):
        state_dict = checkpoint
    else:
        raise TypeError(
            "Unsupported checkpoint format. Expected a state_dict or "
            "{'model_state_dict': state_dict}."
        )

    cleaned = {}
    for key, value in state_dict.items():
        key = key.replace("module.", "")
        cleaned[key] = value.detach().cpu() if hasattr(value, "detach") else torch.as_tensor(value)

    missing = [key for key in REQUIRED_KEYS if key not in cleaned]
    if missing:
        raise KeyError(
            "The checkpoint does not match the expected CNNActorCritic architecture. "
            f"Missing keys: {missing}"
        )

    return cleaned


def pack_weights_as_base64(state_dict: Dict[str, torch.Tensor]) -> str:
    arrays = {}
    for torch_key, export_key in KEY_MAP.items():
        arrays[export_key] = state_dict[torch_key].numpy().astype(np.float32)

    buffer = io.BytesIO()
    np.savez_compressed(buffer, **arrays)
    return base64.b64encode(buffer.getvalue()).decode("ascii")


def build_agent_code(weights_b64: str) -> str:
    return f'''"""
Auto-generated PPO/CNN sailing agent.

Generated by export_ppo_cnn_agent.py.
It contains a NumPy forward pass, compressed weights, preprocessing,
and a one-step safety shield.
"""

from __future__ import annotations

import base64
import io
import math
import numpy as np

try:
    from evaluator.base_agent import BaseAgent
except Exception:
    from agents.base_agent import BaseAgent

GRID = 128
CNN_GRID = 32
BLOCK = GRID // CNN_GRID
GOAL = np.array([64.0, 127.0], dtype=np.float32)

ACTIONS = np.array(
    [
        [0, 1],
        [1, 1],
        [1, 0],
        [1, -1],
        [0, -1],
        [-1, -1],
        [-1, 0],
        [-1, 1],
        [0, 0],
    ],
    dtype=np.float32,
)

_WEIGHTS_B64 = """{weights_b64}"""


def _load_weights():
    raw = base64.b64decode(_WEIGHTS_B64.encode("ascii"))
    data = np.load(io.BytesIO(raw))
    return {{key: data[key].astype(np.float32) for key in data.files}}


WEIGHTS = _load_weights()


def relu(x):
    return np.maximum(x, 0.0)


def linear(x, weight, bias):
    return weight @ x + bias


def conv2d_nchw_single(x, weight, bias, stride=1, padding=0):
    if padding > 0:
        x = np.pad(x, ((0, 0), (padding, padding), (padding, padding)), mode="constant")

    _, _, kernel_h, kernel_w = weight.shape
    windows = np.lib.stride_tricks.sliding_window_view(
        x,
        window_shape=(kernel_h, kernel_w),
        axis=(1, 2),
    )

    if stride > 1:
        windows = windows[:, ::stride, ::stride, :, :]

    y = np.einsum("ockl,cxykl->oxy", weight, windows, optimize=True)
    y += bias[:, None, None]
    return y.astype(np.float32)


def block_mean(x):
    return x.reshape(CNN_GRID, BLOCK, CNN_GRID, BLOCK).mean(axis=(1, 3))


def block_max(x):
    return x.reshape(CNN_GRID, BLOCK, CNN_GRID, BLOCK).max(axis=(1, 3))


def parse_observation(observation):
    pos = observation[0:2].astype(np.float32)
    vel = observation[2:4].astype(np.float32)
    local_wind = observation[4:6].astype(np.float32)

    wind_flat_size = GRID * GRID * 2
    wind_field = observation[6:6 + wind_flat_size].reshape(GRID, GRID, 2).astype(np.float32)
    world = observation[6 + wind_flat_size:].reshape(GRID, GRID).astype(np.float32)

    return pos, vel, local_wind, wind_field, world


def make_cnn_input(observation):
    pos, vel, local_wind, wind_field, world = parse_observation(observation)

    wind_x = block_mean(wind_field[:, :, 0]) / 10.0
    wind_y = block_mean(wind_field[:, :, 1]) / 10.0
    obstacle = block_max(world)

    boat = np.zeros((CNN_GRID, CNN_GRID), dtype=np.float32)
    bx = int(np.clip(pos[0] / BLOCK, 0, CNN_GRID - 1))
    by = int(np.clip(pos[1] / BLOCK, 0, CNN_GRID - 1))
    boat[by, bx] = 1.0

    goal = np.zeros((CNN_GRID, CNN_GRID), dtype=np.float32)
    gx = int(np.clip(GOAL[0] / BLOCK, 0, CNN_GRID - 1))
    gy = int(np.clip(GOAL[1] / BLOCK, 0, CNN_GRID - 1))
    goal[gy, gx] = 1.0

    risk = obstacle.copy()
    for _ in range(2):
        padded = np.pad(risk, 1)
        risk = np.maximum.reduce(
            [
                padded[1:-1, 1:-1],
                padded[:-2, 1:-1],
                padded[2:, 1:-1],
                padded[1:-1, :-2],
                padded[1:-1, 2:],
            ]
        )

    image = np.stack([wind_x, wind_y, obstacle, boat, goal, risk], axis=0).astype(np.float32)

    vector = np.array(
        [
            pos[0] / 127.0,
            pos[1] / 127.0,
            vel[0] / 8.0,
            vel[1] / 8.0,
            local_wind[0] / 10.0,
            local_wind[1] / 10.0,
            np.linalg.norm(GOAL - pos) / 180.0,
        ],
        dtype=np.float32,
    )

    return image, vector


def policy_logits(observation):
    image, vector = make_cnn_input(observation)

    x = conv2d_nchw_single(image, WEIGHTS["conv0_w"], WEIGHTS["conv0_b"], stride=1, padding=1)
    x = relu(x)

    x = conv2d_nchw_single(x, WEIGHTS["conv1_w"], WEIGHTS["conv1_b"], stride=2, padding=1)
    x = relu(x)

    x = conv2d_nchw_single(x, WEIGHTS["conv2_w"], WEIGHTS["conv2_b"], stride=2, padding=1)
    x = relu(x)

    x = x.reshape(-1)
    v = relu(linear(vector, WEIGHTS["vec0_w"], WEIGHTS["vec0_b"]))

    z = np.concatenate([x, v]).astype(np.float32)
    z = relu(linear(z, WEIGHTS["shared0_w"], WEIGHTS["shared0_b"]))
    z = relu(linear(z, WEIGHTS["shared1_w"], WEIGHTS["shared1_b"]))

    return linear(z, WEIGHTS["policy_w"], WEIGHTS["policy_b"])


def sailing_efficiency(direction, wind):
    direction_norm = float(np.linalg.norm(direction))
    wind_norm = float(np.linalg.norm(wind))

    if direction_norm < 1e-9 or wind_norm < 1e-9:
        return 0.05

    boat_direction = direction / direction_norm
    wind_direction = wind / wind_norm
    wind_from = -wind_direction
    wind_angle = math.acos(float(np.clip(np.dot(wind_from, boat_direction), -1.0, 1.0)))

    if wind_angle < math.pi / 4:
        efficiency = 0.05
    elif wind_angle < math.pi / 2:
        efficiency = 0.5 + 0.5 * (wind_angle - math.pi / 4) / (math.pi / 4)
    elif wind_angle < 3 * math.pi / 4:
        efficiency = 1.0
    else:
        efficiency = 1.0 - 0.5 * (wind_angle - 3 * math.pi / 4) / (math.pi / 4)
        efficiency = max(0.5, efficiency)

    return float(efficiency)


def predict_velocity(velocity, wind, action):
    direction = ACTIONS[action].astype(np.float32)
    wind_norm = float(np.linalg.norm(wind))

    if wind_norm <= 1e-9:
        new_velocity = 0.3 * velocity
    else:
        efficiency = sailing_efficiency(direction, wind)
        theoretical_velocity = direction * efficiency * wind_norm * 0.4

        speed = float(np.linalg.norm(theoretical_velocity))
        if speed > 8.0:
            theoretical_velocity = theoretical_velocity / speed * 8.0

        new_velocity = theoretical_velocity + 0.3 * (velocity - theoretical_velocity)

        speed = float(np.linalg.norm(new_velocity))
        if speed > 8.0:
            new_velocity = new_velocity / speed * 8.0

    return np.where(new_velocity < 0, np.ceil(new_velocity), np.floor(new_velocity)).astype(np.float32)


def segment_hits_obstacle(p0, p1, world, margin=1):
    x0, y0 = int(round(float(p0[0]))), int(round(float(p0[1])))
    x1, y1 = int(round(float(p1[0]))), int(round(float(p1[1])))
    n = max(abs(x1 - x0), abs(y1 - y0), 1)

    for k in range(n + 1):
        x = int(round(x0 + (x1 - x0) * k / n))
        y = int(round(y0 + (y1 - y0) * k / n))

        if x < 0 or x >= GRID or y < 0 or y >= GRID:
            return True

        x_min, x_max = max(0, x - margin), min(GRID, x + margin + 1)
        y_min, y_max = max(0, y - margin), min(GRID, y + margin + 1)

        if np.any(world[y_min:y_max, x_min:x_max] > 0.5):
            return True

    return False


def safe_action(observation, proposed_action):
    pos, vel, local_wind, wind_field, world = parse_observation(observation)

    proposed_velocity = predict_velocity(vel, local_wind, proposed_action)
    proposed_pos = np.clip(pos + proposed_velocity, [0, 0], [127, 127])

    if not segment_hits_obstacle(pos, proposed_pos, world, margin=1):
        return int(proposed_action)

    to_goal = GOAL - pos
    dist_goal = float(np.linalg.norm(to_goal)) + 1e-9
    direction_goal = to_goal / dist_goal

    best_action = 8
    best_score = -1e18

    for action in range(9):
        next_velocity = predict_velocity(vel, local_wind, action)
        next_pos = np.clip(pos + next_velocity, [0, 0], [127, 127])

        if segment_hits_obstacle(pos, next_pos, world, margin=2):
            continue

        new_dist = float(np.linalg.norm(GOAL - next_pos))
        progress = dist_goal - new_dist
        vmg = float(np.dot(next_velocity, direction_goal))
        efficiency = sailing_efficiency(ACTIONS[action], local_wind)
        score = 2.5 * progress + 0.8 * vmg + 0.5 * efficiency

        if action == 8:
            score -= 1.0

        if score > best_score:
            best_score = score
            best_action = action

    return int(best_action)


class MyAgent(BaseAgent):
    def __init__(self):
        super().__init__()
        self.np_random = np.random.default_rng(0)

    def act(self, observation):
        logits = policy_logits(observation)
        ranked_actions = np.argsort(-logits)

        for action in ranked_actions:
            action = int(action)
            safe = safe_action(observation, action)
            if safe == action:
                return action

        return safe_action(observation, int(ranked_actions[0]))

    def reset(self):
        pass

    def seed(self, seed=None):
        self.np_random = np.random.default_rng(seed)
'''


def export(checkpoint_path: Path, output_path: Path) -> None:
    state_dict = load_state_dict(checkpoint_path)
    weights_b64 = pack_weights_as_base64(state_dict)
    agent_code = build_agent_code(weights_b64)

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(agent_code, encoding="utf-8")

    print(f"Wrote {output_path}")
    print("The generated file is standalone and contains compressed NumPy weights.")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--checkpoint",
        type=Path,
        default=Path("artifacts/ppo_cnn_policy.pt"),
        help="Path to the trained PPO/CNN checkpoint.",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=Path("src/agents/proposed_agent.py"),
        help="Path of the generated standalone agent.",
    )
    args = parser.parse_args()

    export(args.checkpoint, args.output)


if __name__ == "__main__":
    main()
