#!/usr/bin/env python3
"""Export a trained PyTorch PPO/CNN policy to a single NumPy-only Codabench agent file."""

from __future__ import annotations

import argparse
import base64
import io
import textwrap
from pathlib import Path

import numpy as np
import torch

# Reuse the network class so checkpoint names are consistent.
from train_ppo_cnn_safety import PolicyNet


AGENT_TEMPLATE = r'''
"""
Codabench submission agent for stable_v2_RL_sailing_challenge.
Generated by export_policy_to_agent.py.
Uses only numpy at inference time: CNN policy + one-step safety shield.
"""

import base64
import io
import math
import zipfile
import numpy as np

try:
    from evaluator.base_agent import BaseAgent
except Exception:
    try:
        from agents.base_agent import BaseAgent
    except Exception:
        class BaseAgent:
            def reset(self): pass
            def seed(self, seed=None): pass

GRID = 128
IMG = 32
BLOCK = 4
WORLD_SIZE = GRID * GRID
WIND_SIZE = WORLD_SIZE * 2
GOAL = np.array([64.0, 127.0], dtype=np.float32)
ACTIONS = np.array([[0,1],[1,1],[1,0],[1,-1],[0,-1],[-1,-1],[-1,0],[-1,1],[0,0]], dtype=np.float32)

WEIGHTS_B64 = "__WEIGHTS_B64__"


def _load_npz_from_b64(s):
    data = base64.b64decode(s.encode("ascii"))
    return dict(np.load(io.BytesIO(data)))


def parse_observation(obs):
    obs = np.asarray(obs, dtype=np.float32)
    pos = obs[0:2].astype(np.float32)
    vel = obs[2:4].astype(np.float32)
    wind = obs[6:6 + WIND_SIZE].reshape(GRID, GRID, 2).astype(np.float32)
    world = obs[6 + WIND_SIZE:6 + WIND_SIZE + WORLD_SIZE].reshape(GRID, GRID).astype(np.float32)
    return pos, vel, wind, world


def block_mean_2d(x):
    return x.reshape(IMG, BLOCK, IMG, BLOCK).mean(axis=(1, 3))


def block_max_2d(x):
    return x.reshape(IMG, BLOCK, IMG, BLOCK).max(axis=(1, 3))


def preprocess(obs):
    pos, vel, wind, world = parse_observation(obs)
    x, y = float(pos[0]), float(pos[1])
    vx, vy = float(vel[0]), float(vel[1])
    wx, wy = float(obs[4]), float(obs[5])
    wind_x = np.clip(block_mean_2d(wind[:, :, 0]) / 10.0, -2.0, 2.0)
    wind_y = np.clip(block_mean_2d(wind[:, :, 1]) / 10.0, -2.0, 2.0)
    obstacle = block_max_2d(world)
    boat = np.zeros((IMG, IMG), dtype=np.float32)
    bx = int(np.clip(x / BLOCK, 0, IMG - 1))
    by = int(np.clip(y / BLOCK, 0, IMG - 1))
    boat[by, bx] = 1.0
    goal = np.zeros((IMG, IMG), dtype=np.float32)
    goal[IMG - 1, max(0, IMG // 2 - 1):min(IMG, IMG // 2 + 2)] = 1.0
    image = np.stack([wind_x, wind_y, obstacle, boat, goal], axis=0).astype(np.float32)[None, :, :, :]
    to_goal = GOAL - pos
    dist = float(np.linalg.norm(to_goal) + 1e-6)
    angle = math.atan2(float(to_goal[1]), float(to_goal[0]))
    vec = np.array([[x / 127.0, y / 127.0, vx / 8.0, vy / 8.0, wx / 10.0, wy / 10.0,
                     to_goal[0] / 127.0, to_goal[1] / 127.0, dist / 180.0,
                     math.sin(angle), math.cos(angle), (x - 64.0) / 64.0]], dtype=np.float32)
    return image, vec


def relu(x):
    return np.maximum(x, 0.0)


def linear(x, w, b):
    return x @ w.T + b


def conv2d_nchw(x, w, b, stride=1, padding=0):
    # x: N,C,H,W ; w: O,C,KH,KW
    if padding:
        x = np.pad(x, ((0, 0), (0, 0), (padding, padding), (padding, padding)), mode="constant")
    n, c, h, ww = x.shape
    o, _, kh, kw = w.shape
    oh = (h - kh) // stride + 1
    ow = (ww - kw) // stride + 1
    y = np.empty((n, o, oh, ow), dtype=np.float32)
    for i in range(oh):
        hs = i * stride
        for j in range(ow):
            ws = j * stride
            patch = x[:, :, hs:hs + kh, ws:ws + kw]
            y[:, :, i, j] = np.tensordot(patch, w, axes=([1, 2, 3], [1, 2, 3])) + b
    return y


def sailing_efficiency(direction, wind):
    wind_norm = np.linalg.norm(wind)
    direction_norm = np.linalg.norm(direction)
    if wind_norm < 1e-10 or direction_norm < 1e-10:
        direction = np.array([1.0, 0.0], dtype=np.float32)
        direction_norm = 1.0
    wind_direction = wind / max(float(wind_norm), 1e-10)
    boat_direction = direction / max(float(direction_norm), 1e-10)
    wind_from = -wind_direction
    wind_angle = math.acos(float(np.clip(np.dot(wind_from, boat_direction), -1.0, 1.0)))
    if wind_angle < math.pi / 4:
        eff = 0.05
    elif wind_angle < math.pi / 2:
        eff = 0.5 + 0.5 * (wind_angle - math.pi / 4) / (math.pi / 4)
    elif wind_angle < 3 * math.pi / 4:
        eff = 1.0
    else:
        eff = 1.0 - 0.5 * (wind_angle - 3 * math.pi / 4) / (math.pi / 4)
        eff = max(0.5, eff)
    return float(eff)


class SafetyShield:
    def __init__(self, boat_performance=0.4, max_speed=8.0, inertia_factor=0.3):
        self.boat_performance = boat_performance
        self.max_speed = max_speed
        self.inertia_factor = inertia_factor

    def simulate(self, obs, action):
        pos, vel, _wind_field, world = parse_observation(obs)
        wind = obs[4:6].astype(np.float32)
        direction = ACTIONS[int(action)]
        wind_norm = float(np.linalg.norm(wind))
        eff = sailing_efficiency(direction, wind)
        theoretical = direction * eff * wind_norm * self.boat_performance
        speed = float(np.linalg.norm(theoretical))
        if speed > self.max_speed:
            theoretical = theoretical / speed * self.max_speed
        new_vel = theoretical + self.inertia_factor * (vel - theoretical)
        speed = float(np.linalg.norm(new_vel))
        if speed > self.max_speed:
            new_vel = new_vel / speed * self.max_speed
        new_vel_i = np.where(new_vel < 0, np.ceil(new_vel), np.floor(new_vel)).astype(np.int32)
        new_pos = np.clip(pos.astype(np.int32) + new_vel_i, [0, 0], [GRID - 1, GRID - 1]).astype(np.int32)
        unsafe = self._hits_obstacle(pos.astype(np.int32), new_pos, world)
        score = self._score_action(pos, new_pos.astype(np.float32), new_vel_i.astype(np.float32), world, unsafe)
        return new_pos.astype(np.float32), new_vel_i.astype(np.float32), unsafe, score

    def _hits_obstacle(self, old_pos, new_pos, world):
        x1, y1 = int(new_pos[0]), int(new_pos[1])
        if world[y1, x1] > 0.5:
            return True
        dx = int(new_pos[0] - old_pos[0])
        dy = int(new_pos[1] - old_pos[1])
        n = max(abs(dx), abs(dy), 1)
        for k in range(1, n + 1):
            x = int(round(old_pos[0] + dx * k / n))
            y = int(round(old_pos[1] + dy * k / n))
            if 0 <= x < GRID and 0 <= y < GRID and world[y, x] > 0.5:
                return True
        return False

    def _local_obstacle_penalty(self, pos, world, radius=5):
        x, y = int(pos[0]), int(pos[1])
        x0, x1 = max(0, x - radius), min(GRID, x + radius + 1)
        y0, y1 = max(0, y - radius), min(GRID, y + radius + 1)
        patch = world[y0:y1, x0:x1]
        if patch.max() < 0.5:
            return 0.0
        ys, xs = np.where(patch > 0.5)
        if len(xs) == 0:
            return 0.0
        d2 = (xs + x0 - x) ** 2 + (ys + y0 - y) ** 2
        return max(0.0, radius - math.sqrt(float(np.min(d2)))) / radius

    def _score_action(self, old_pos, new_pos, new_vel, world, unsafe):
        if unsafe:
            return -1e9
        old_dist = float(np.linalg.norm(GOAL - old_pos))
        new_dist = float(np.linalg.norm(GOAL - new_pos))
        progress = old_dist - new_dist
        dy = float(new_pos[1] - old_pos[1])
        center_pen = abs(float(new_pos[0]) - 64.0) / 64.0
        obstacle_pen = self._local_obstacle_penalty(new_pos, world, radius=5)
        return 1.8 * progress + 0.35 * dy + 0.10 * float(new_vel[1]) - 0.05 * center_pen - 0.60 * obstacle_pen

    def filter(self, obs, proposed_action):
        proposed_action = int(proposed_action)
        _, _, unsafe, _ = self.simulate(obs, proposed_action)
        if not unsafe:
            return proposed_action
        best_a, best_score = 8, -1e18
        for a in range(9):
            _, _, u, s = self.simulate(obs, a)
            if not u and s > best_score:
                best_a, best_score = a, s
        return int(best_a)


class NumpyPolicy:
    def __init__(self):
        self.w = _load_npz_from_b64(WEIGHTS_B64)

    def __call__(self, image, vec):
        w = self.w
        x = relu(conv2d_nchw(image, w["cnn.0.weight"], w["cnn.0.bias"], stride=2, padding=2))
        x = relu(conv2d_nchw(x, w["cnn.2.weight"], w["cnn.2.bias"], stride=2, padding=1))
        x = relu(conv2d_nchw(x, w["cnn.4.weight"], w["cnn.4.bias"], stride=2, padding=1))
        x = x.reshape((x.shape[0], -1))
        v = relu(linear(vec, w["vec_net.0.weight"], w["vec_net.0.bias"]))
        v = relu(linear(v, w["vec_net.2.weight"], w["vec_net.2.bias"]))
        z = np.concatenate([x, v], axis=1)
        z = relu(linear(z, w["trunk.0.weight"], w["trunk.0.bias"]))
        z = relu(linear(z, w["trunk.2.weight"], w["trunk.2.bias"]))
        logits = linear(z, w["actor.weight"], w["actor.bias"])
        return logits[0]


class MyAgent(BaseAgent):
    def __init__(self):
        super().__init__()
        self.policy = NumpyPolicy()
        self.shield = SafetyShield()
        self.np_random = np.random.default_rng()

    def act(self, observation):
        image, vec = preprocess(observation)
        logits = self.policy(image, vec)
        proposed = int(np.argmax(logits))
        return self.shield.filter(observation, proposed)

    def reset(self):
        pass

    def seed(self, seed=None):
        self.np_random = np.random.default_rng(seed)
'''


def main() -> None:
    p = argparse.ArgumentParser()
    p.add_argument("--checkpoint", required=True, help="Path to best_model.pt or last_model.pt")
    p.add_argument("--out", default="my_agent.py", help="Output submission file")
    args = p.parse_args()

    checkpoint = torch.load(args.checkpoint, map_location="cpu")
    state = checkpoint.get("model_state_dict", checkpoint)
    model = PolicyNet()
    model.load_state_dict(state)
    model.eval()

    arrays = {}
    for k, v in model.state_dict().items():
        # Critic is not needed for inference, but keeping it would only enlarge the file.
        if k.startswith("critic"):
            continue
        arrays[k] = v.detach().cpu().numpy().astype(np.float32)

    buf = io.BytesIO()
    np.savez_compressed(buf, **arrays)
    encoded = base64.b64encode(buf.getvalue()).decode("ascii")

    code = AGENT_TEMPLATE.replace("__WEIGHTS_B64__", encoded)
    Path(args.out).write_text(code, encoding="utf-8")
    print(f"Wrote {args.out}")
    print("Create the submission zip with: zip my_submission.zip " + str(Path(args.out).name))


if __name__ == "__main__":
    main()
